# Generated by Django 4.0 on 2022-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0004_alter_profile_dob_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired')], max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
    ]
