# Generated by Django 4.0 on 2022-01-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0006_bookappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
